### ISSUE TITLE
directed graph?

### ISSUE THREAD

**Issue by snaketron** [snaketron/ClustIRR#28]
https://github.com/snaketron/ClustIRR/blob/531e13aa1969e4b94f6e432d0f3457809df00c98/R/graph.R#L120C11-L120C32

@kaozkai 

I though we were creating undirected (simple) graph. Is this correct?

**Comment by kaozkai** [comment]
yes, this had to be set to "directed" to get the correct attributes (cdr3 sequences) from igraph.
when using "undirected" the id's were switched in some cases, which lead to incorrect associations of the "from" and "to" cdr3-seqs.

this should not matter, as no further igraph-functions are called on this object.
in future revisions maybe this igraph-conversion route could be replaced somehow, as we opted to not support this igraph-objects to the user for now because of this issue.

in my thesis / clustirr-diff branch i actually had to build new igraph-objects before calculating community detection etc
